services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql # your existing DB volume
      - /home/wbrigham/projects/sql-data-warehouse-project:/repo # <-- NEW MOUNT

volumes:
  sqlserver_data:
